### ISSUE TITLE
Add "Instagram" as social icon as page footer

### ISSUE THREAD

**Issue by 0xDTE** [vemurikarthik/landy-react-template#15]

**Comment by vemurikarthik** [comment]
torvalds.dev is analyzing the ticket

**Comment by vemurikarthik** [comment]
Based on the code you've provided, it seems you're working with a React app, specifically the page footer. 

Here is a strategic plan for how to add an "Instagram" social icon to your page footer:

1. **Inspect the current implementation of social icons:** Looking at the footer files `src/components/Footer/index.tsx` and `src/components/Footer/styles.ts`, it’s clear that the social icons are SVG images. They're placed in the footer with href attributes linking out to their corresponding social media sites. A new "Instagram" icon would probably follow a similar pattern.

2. **Obtain and add the SVG file for the Instagram icon:** You will need an SVG file for the Instagram icon, named `instagram.svg`. This file should be added to the appropriate directory where your other social SVGs are located.

3. **Update the Footer React component:** Add a new `SocialLink` component for Instagram in `src/components/Footer/index.tsx`. Ensure this new link properly points to the desired Instagram page via its `href` attribute.

The `Footer` component and styles are contained within the files `src/components/Footer/index.tsx` and `src/components/Footer/styles.ts` respectively, so those would be the key files in need of updating. 

The file `src/common/ScrollToTop/index.tsx` seems unrelated to the footer or your social links, so it's unlikely that you'll need to modify this file for this particular task.

Here's a possible example of how to add this to the `Footer` component depending on where you want it:

```jsx
<SocialLink
   href="https://www.instagram.com/yourInstagramHandle/"
   src="instagram.svg"
/>
```

Replace `yourInstagramHandle` with the desired Instagram username. The `src` attribute might need to be updated depending on where you place your Instagram SVG file. 

You'll also need to place this `SocialLink` in the footer where you would like the Instagram icon to appear. The current social links are within the `FooterContainer` so that could be a good location for the Instagram link as well.
