### ISSUE TITLE
Add instagram as a social icon in the landing page between github and twitter

### ISSUE THREAD

**Issue by 0xDTE** [vemurikarthik/landy-react-template#17]

**Comment by vemurikarthik** [comment]
torvalds.dev is analyzing the ticket

**Comment by vemurikarthik** [comment]
To add the Instagram social icon in the landing page between Github and Twitter in your React application, multiple steps will be involved. 

Before providing the steps, let's understand the affected files:

1. **src/components/Footer/index.tsx**: This is likely where you will add the Instagram icon. The `SocialLink` component is used to render the social media icons. An instance of this component with href pointing to Instagram URL and src being the name of Instagram svg file will be added.

2. **public/manifest.json**: Changes may be needed in manifest if the Instagram svg file will be a part of the app icons. You might add a new icon entry here.

3. **src/content/IntroContent.json, src/content/MiddleBlockContent.json**: These files don't seem have direct relevance to the task since they just contain some content for the landing page and middle block component, respectively.

Here is the general plan: 

1. Obtain or create a SVG file for the Instagram icon: This file should be kept in the same directory where other social icons svg files are kept.

2. Update src/components/Footer/index.tsx: Introduce an instance of `SocialLink` to incorporate Instagram icon and link.

Note: Before executing these steps, ensure to have a clear understanding of the directory structure and paths in the files. The path where the svg file is placed should be correct while using it in the code.
